// Code generated by girgen. DO NOT EDIT.

package gstnet

import (
	_ "runtime/cgo"
)

// #cgo pkg-config: gstreamer-net-1.0 gstreamer-1.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <gst/net/net.h>
import "C"
