// Code generated by girgen. DO NOT EDIT.

package gstvideo

import (
	"unsafe"

	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <gst/video/video.h>
import "C"

//export _gotk4_gstvideo1_ColorBalance_ConnectValueChanged
func _gotk4_gstvideo1_ColorBalance_ConnectValueChanged(arg0 C.gpointer, arg1 *C.GstColorBalanceChannel, arg2 C.gint, arg3 C.guintptr) {
	var f func(channel *ColorBalanceChannel, value int)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg3))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(channel *ColorBalanceChannel, value int))
	}

	var _channel *ColorBalanceChannel // out
	var _value int                    // out

	_channel = wrapColorBalanceChannel(coreglib.Take(unsafe.Pointer(arg1)))
	_value = int(arg2)

	f(_channel, _value)
}
