// Code generated by girgen. DO NOT EDIT.

package gstaudio

// #include <stdlib.h>
// #include <gst/audio/audio.h>
import "C"

// AUDIO_RESAMPLER_OPT_CUBIC_B: g_TYPE_DOUBLE, B parameter of the cubic filter.
// Values between 0.0 and 2.0 are accepted. 1.0 is the default.
//
// Below are some values of popular filters: B C Hermite 0.0 0.0 Spline 1.0 0.0
// Catmull-Rom 0.0 1/2.
const AUDIO_RESAMPLER_OPT_CUBIC_B = "GstAudioResampler.cubic-b"

// AUDIO_RESAMPLER_OPT_CUBIC_C: g_TYPE_DOUBLE, C parameter of the cubic filter.
// Values between 0.0 and 2.0 are accepted. 0.0 is the default.
//
// See T_AUDIO_RESAMPLER_OPT_CUBIC_B for some more common values.
const AUDIO_RESAMPLER_OPT_CUBIC_C = "GstAudioResampler.cubic-c"

// AUDIO_RESAMPLER_OPT_CUTOFF: g_TYPE_DOUBLE, Cutoff parameter for the filter.
// 0.940 is the default.
const AUDIO_RESAMPLER_OPT_CUTOFF = "GstAudioResampler.cutoff"

// AUDIO_RESAMPLER_OPT_FILTER_INTERPOLATION:
// GST_TYPE_AUDIO_RESAMPLER_INTERPOLATION: how the filter coefficients should be
// interpolated. GST_AUDIO_RESAMPLER_FILTER_INTERPOLATION_CUBIC is default.
const AUDIO_RESAMPLER_OPT_FILTER_INTERPOLATION = "GstAudioResampler.filter-interpolation"

// AUDIO_RESAMPLER_OPT_FILTER_MODE: GST_TYPE_AUDIO_RESAMPLER_FILTER_MODE: how
// the filter tables should be constructed. GST_AUDIO_RESAMPLER_FILTER_MODE_AUTO
// is the default.
const AUDIO_RESAMPLER_OPT_FILTER_MODE = "GstAudioResampler.filter-mode"

// AUDIO_RESAMPLER_OPT_FILTER_MODE_THRESHOLD: g_TYPE_UINT: the amount of memory
// to use for full filter tables before switching to interpolated filter tables.
// 1048576 is the default.
const AUDIO_RESAMPLER_OPT_FILTER_MODE_THRESHOLD = "GstAudioResampler.filter-mode-threshold"

// AUDIO_RESAMPLER_OPT_FILTER_OVERSAMPLE: g_TYPE_UINT, oversampling to use when
// interpolating filters 8 is the default.
const AUDIO_RESAMPLER_OPT_FILTER_OVERSAMPLE = "GstAudioResampler.filter-oversample"

// AUDIO_RESAMPLER_OPT_MAX_PHASE_ERROR: g_TYPE_DOUBLE: The maximum allowed phase
// error when switching sample rates. 0.1 is the default.
const AUDIO_RESAMPLER_OPT_MAX_PHASE_ERROR = "GstAudioResampler.max-phase-error"

// AUDIO_RESAMPLER_OPT_N_TAPS: g_TYPE_INT: the number of taps to use for the
// filter. 0 is the default and selects the taps automatically.
const AUDIO_RESAMPLER_OPT_N_TAPS = "GstAudioResampler.n-taps"

// AUDIO_RESAMPLER_OPT_STOP_ATTENUATION: g_TYPE_DOUBLE, stopband attenuation in
// decibels. The attenuation after the stopband for the kaiser window. 85 dB is
// the default.
const AUDIO_RESAMPLER_OPT_STOP_ATTENUATION = "GstAudioResampler.stop-attenutation"

// AUDIO_RESAMPLER_OPT_TRANSITION_BANDWIDTH: g_TYPE_DOUBLE, transition
// bandwidth. The width of the transition band for the kaiser window. 0.087 is
// the default.
const AUDIO_RESAMPLER_OPT_TRANSITION_BANDWIDTH = "GstAudioResampler.transition-bandwidth"
const AUDIO_RESAMPLER_QUALITY_DEFAULT = 4
const AUDIO_RESAMPLER_QUALITY_MAX = 10
const AUDIO_RESAMPLER_QUALITY_MIN = 0
